### server port
server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include=*:
school:
  datasource:
    url: jdbc:mysql://localhost:3306/education_school?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
student:
  datasource:
    url: jdbc:mysql://localhost:3306/education_student?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000